// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderService.DataAccess.SQL;

namespace OrderService.DataAccess.SQL.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20210217120329_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("OrderService.Shared.Model.OrderDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BillingAddressId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<short>("OrderStatus")
                        .HasColumnType("smallint");

                    b.Property<string>("PaymentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromotionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceipentAddressId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4d4b8bcc-66d1-42b2-a0fa-dde8ba2c9d8e"),
                            BillingAddressId = "New Address",
                            CreatedAt = new DateTime(2021, 2, 17, 17, 33, 29, 376, DateTimeKind.Local).AddTicks(2297),
                            CustomerId = "f9d7cd3b-bd1d-4b0c-9eda-081b59335c97",
                            InvoiceNumber = "#12345",
                            ModifiedDate = new DateTime(2021, 2, 17, 17, 33, 29, 377, DateTimeKind.Local).AddTicks(2359),
                            OrderDate = new DateTime(2021, 2, 17, 17, 33, 29, 377, DateTimeKind.Local).AddTicks(2856),
                            OrderStatus = (short)0,
                            PaymentId = "eb3a097c-d677-4f76-9dcc-265e7cf7baaa",
                            PromotionId = "#1qaz2wsx",
                            ReceipentAddressId = "New Address"
                        },
                        new
                        {
                            Id = new Guid("7668eea2-23b7-481b-bae4-b35b62b8cab2"),
                            BillingAddressId = "Old Address",
                            CreatedAt = new DateTime(2021, 2, 17, 17, 33, 29, 377, DateTimeKind.Local).AddTicks(5130),
                            CustomerId = "36192d7f-0987-4db5-a47f-240bfb80f5de",
                            InvoiceNumber = "#4567",
                            ModifiedDate = new DateTime(2021, 2, 17, 17, 33, 29, 377, DateTimeKind.Local).AddTicks(5182),
                            OrderDate = new DateTime(2021, 2, 17, 17, 33, 29, 377, DateTimeKind.Local).AddTicks(5192),
                            OrderStatus = (short)1,
                            PaymentId = "9a9367ab-db44-4953-800e-fea964f2f52f",
                            PromotionId = "#3edc$RFV",
                            ReceipentAddressId = "Old Address"
                        });
                });

            modelBuilder.Entity("OrderService.Shared.Model.ProductOrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ProductOrderDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
