// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderService.DataAccess.SQL;

namespace OrderService.DataAccess.SQL.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class OrderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("OrderService.Shared.Model.OrderDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromotionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99a673d1-957a-435c-8ce5-b5cff95f8732"),
                            AddressId = "New Address",
                            CreatedAt = new DateTime(2021, 2, 14, 15, 22, 8, 500, DateTimeKind.Local).AddTicks(435),
                            CustomerId = "a343e671-93af-47cb-b7a8-99fac10f1f01",
                            InvoiceNumber = "#12345",
                            ModifiedDate = new DateTime(2021, 2, 14, 15, 22, 8, 503, DateTimeKind.Local).AddTicks(2196),
                            OrderDate = new DateTime(2021, 2, 14, 15, 22, 8, 503, DateTimeKind.Local).AddTicks(2754),
                            OrderStatus = "Confirmed",
                            PaymentId = "33bafcb3-ccc7-435d-98fc-49f4b13cd71a",
                            PromotionId = "#1qaz2wsx"
                        },
                        new
                        {
                            Id = new Guid("5fac4791-15bb-453a-aaa9-5ed35f62f1de"),
                            AddressId = "Old Address",
                            CreatedAt = new DateTime(2021, 2, 14, 15, 22, 8, 503, DateTimeKind.Local).AddTicks(5270),
                            CustomerId = "54ca7ed4-0042-4a0f-97ff-c0f9fad12c43",
                            InvoiceNumber = "#4567",
                            ModifiedDate = new DateTime(2021, 2, 14, 15, 22, 8, 503, DateTimeKind.Local).AddTicks(5321),
                            OrderDate = new DateTime(2021, 2, 14, 15, 22, 8, 503, DateTimeKind.Local).AddTicks(5330),
                            OrderStatus = "Awaiting",
                            PaymentId = "e5c70f5f-3cdd-43ed-a1cc-d009fe7e0166",
                            PromotionId = "#3edc$RFV"
                        });
                });

            modelBuilder.Entity("OrderService.Shared.Model.ProductOrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ProductOrderDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
