// <auto-generated />
using System;
using CartService.DataAccess.SQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CartService.DataAccess.SQL.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20210214142158_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CartService.DataAccess.SQL.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Cart");

                    b.HasData(
                        new
                        {
                            Id = new Guid("325c5ee8-ba74-47c5-9e4c-a8bd24a9b570"),
                            CreatedAt = new DateTime(2021, 2, 14, 15, 21, 57, 806, DateTimeKind.Local).AddTicks(6476),
                            CustomerId = "RAHULXXXX123",
                            ModifiedDate = new DateTime(2021, 2, 14, 15, 21, 57, 806, DateTimeKind.Local).AddTicks(8462)
                        },
                        new
                        {
                            Id = new Guid("8fa73bc7-fe97-4c67-9ac3-2991958f6469"),
                            CreatedAt = new DateTime(2021, 4, 5, 15, 21, 57, 806, DateTimeKind.Local).AddTicks(9027),
                            CustomerId = "RAHULXXXX123",
                            ModifiedDate = new DateTime(2021, 4, 5, 15, 21, 57, 806, DateTimeKind.Local).AddTicks(9075)
                        });
                });

            modelBuilder.Entity("CartService.DataAccess.SQL.CartProductMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CartId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKU")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CartProductMapping");
                });
#pragma warning restore 612, 618
        }
    }
}
