// <auto-generated />
using System;
using CartService.DataAccess.SQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CartService.DataAccess.SQL.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20210218110924_Update-db-schema")]
    partial class Updatedbschema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CartService.DataAccess.SQL.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Cart");

                    b.HasData(
                        new
                        {
                            Id = new Guid("56bf938d-f7a5-42fc-a9d8-6b6a9172ba7a"),
                            CreatedAt = new DateTime(2021, 2, 18, 12, 9, 24, 490, DateTimeKind.Local).AddTicks(4610),
                            CustomerId = "RAHULXXXX123",
                            ModifiedDate = new DateTime(2021, 2, 18, 12, 9, 24, 490, DateTimeKind.Local).AddTicks(7301)
                        },
                        new
                        {
                            Id = new Guid("dd5cb491-0261-49a9-9171-32dff07b5c25"),
                            CreatedAt = new DateTime(2021, 4, 9, 12, 9, 24, 490, DateTimeKind.Local).AddTicks(8134),
                            CustomerId = "RAHULXXXX123",
                            ModifiedDate = new DateTime(2021, 4, 9, 12, 9, 24, 490, DateTimeKind.Local).AddTicks(8207)
                        });
                });

            modelBuilder.Entity("CartService.DataAccess.SQL.CartProductMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CartId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CartProductMapping");
                });
#pragma warning restore 612, 618
        }
    }
}
